# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac36c126b5e7a2f47b07dff516f221b2bc789fbb75bb51bb684b39747d93209abe986ba1f67f59eda804a742b9cecb222d63c953230504e3d233db32b82f6735

test:
  secret_key_base: 02ccf0576cca5c5b622601a1cd719c24bb475fb4c2e3cf62a05e6d3006f6c9cebce3bee8f482242b4a1f496caa2a474567c44e87c33c6346362cdb9428a1d44d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
